on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        id: trufflehog_scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
        continue-on-error: false

      # Conditional email notification if secrets are detected
      - name: Send Email Notification
        if: failure()  # This step runs only if the previous step fails
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Secret Detected in Repository"
          to: "samarthgudadinni@gmail.com"
          from: "testmedusamonitor@gmail.com"
          body: "Trufflehog detected a potential secret in the latest commit. Please review the Actions log for details."
