on:
  push:
    branches:
      - '**'       # Matches all branches
  pull_request:
    branches:
      - '**'       # Matches all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        id: trufflehog_scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
        continue-on-error: false  # Fail the job if secrets are found

      - name: Slack Notification
        if: failure()  # Run this step only if the Secret Scanning step fails
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "🚨 *Secret Detected in Repository*: Trufflehog has flagged a potential secret in the latest commit. Please review the Actions log for details."}' \
          $SLACK_WEBHOOK_URL
